### ISSUE TITLE
fallback to std::call_once if exists

### ISSUE THREAD

**Issue by dmorilha** [boostorg/coroutine#19]
Hi, could we fallback to std::call_once[1](http://en.cppreference.com/w/cpp/thread/call_once) in case it exists? That would eliminate the boost_thread requirement when compiling with C++11 (or above) and reduce complexity.

**Comment by dmorilha** [comment]
I've created this patch: https://gist.github.com/dmorilha/10ab1090d0f374c75902

**Comment by olk** [comment]
should already be fixed - linking against boost.thread only if std::call_once is not supported
