### ISSUE TITLE
Boost.Coroutine overview wrong like to Boost.Coroutines2

### ISSUE THREAD

**Issue by ipapadop** [boostorg/coroutine#26]
In http://www.boost.org/doc/libs/1_62_0/libs/coroutine/doc/html/coroutine/overview.html the link to Boost.Coroutine2 is incorrect: http://www.boost.org/doc/libs/1_62_0/libs/coroutine2/index.htmlBoo.Coroutine2

**Comment by olk** [comment]
fixed, thx
