### ISSUE TITLE
same_fringe.cpp does not compare fringe

### ISSUE THREAD

**Issue by badfd** [boostorg/coroutine#40]
Dale Schumacher in ["Same Fringe" Revisited](http://www.dalnefre.com/wp/2017/01/same-fringe-revisited/) says that the fringe of a tree "... is simply the sequence of leaves reading from left to right."

The coroutine example, **same_fringe.cpp**, includes non-leaf values amongst its comparisons. Perhaps the example could be renamed, or reworked to behave as expected.

**Comment by olk** [comment]
example is good as it is to get an idea how to use coroutine
