### ISSUE TITLE
MinGW-w64 undefined reference to __imp_make_fcontext / __imp_jump_fcontext

### ISSUE THREAD

**Issue by brechtsanders** [boostorg/coroutine#50]
I keep getting undefined refence errors from the linker while the symbols do exist in `.asm` files.
For example `_make_fcontext` is defined in `libs/context/src/asm/make_i386_ms_pe_gas.asm` and `libs/context/src/asm/make_x86_64_ms_pe_gas.asm`.
However I have a suspicion the linker is looking for `make_fcontext` (without leading underscore).

Boost version: 1.73.0, but also have this problem with older versions
OS: Windows 10
Shell: MSYS2
Compiler toolset: MinGW-w64 GCC for Windows from http://winlibs.com/ (different versions, e.g. GCC 9.3.0)
Build command (+ the same with `address-model=32`):
```
BOOST_ROOT=$(pwd) MINGW=/ tools/build/src/engine/bjam.exe -q --prefix=/usr/local --build-dir=build_win --build-type=complete --layout=tagged --enable-icu --disable-filesystem2 toolset=gcc target-os=windows abi=ms link=static,shared runtime-link=static,shared variant=release threading=single,multi threadapi=win32 context-impl=winfib address-model=64 --without-python --without-mpi release stage cxxflags="-fpermissive -DBOOST_LOG_WITHOUT_SYSLOG"
```

```
gcc.link.dll build_win\boost\bin.v2\libs\coroutine\build\gcc-10.1.0\release\context-impl-winfib\threadapi-win32\visibility-hidden\libboost_coroutine-x64.dll.a
d:/prog/winlibs64-10.1.0/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build_win\boost\bin.v2\libs\coroutine\build\gcc-10.1.0\release\context-impl-winfib\threadapi-win32\visibility-hidden\detail\coroutine_context.o:coroutine_context.cpp:(.text+0x4f): undefined reference to
`__imp_make_fcontext'
d:/prog/winlibs64-10.1.0/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build_win\boost\bin.v2\libs\coroutine\build\gcc-10.1.0\release\context-impl-winfib\threadapi-win32\visibility-hidden\detail\coroutine_context.o:coroutine_context.cpp:(.text+0xd7): undefined reference to
`__imp_jump_fcontext'
```

**Comment by brechtsanders** [comment]
FYI: I just tried to use jwasm to see what happens.
If I run:
```
sed -i.bak -e "s/^.386/.686/; s/stmxcsr/STMXCSR/; s/ldmxcsr/LDMXCSR/; s/jump_fcontext/_&/" libs/context/src/asm/jump_i386_ms_pe_masm.asm
jwasm $(if ( echo $RUNPLATFORM | grep -q x86_64 ); then echo "-win64"; else echo "-coff"; fi) -Fobuild_win/boost/bin.v2/libs/context/build/gcc-10.1.0/release/link-static/threading-multi/visibility-hidden/asm/jump_i386_ms_pe_gas.o libs/context/src/asm/jump_i386_ms_pe_masm.asm
```
I still get:
```
d:/prog/winlibs32-10.1.0/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export _jump_fcontext: symbol not found
```
so it really seems to look like the linker can't find the symbol in the object file generated by the assembler (either GNU Assembler or JWasm).

**Comment by brechtsanders** [comment]
After a lot of trial and error I noticed the link error disappears when I remove the leading underscore from the export directive in the `.asm`files, e.g. replacing this:
```
.section .drectve
.ascii " -export:\"_jump_fcontext\""
```
with:
```
.section .drectve
.ascii " -export:\"jump_fcontext\""
```

FYI: I fixed it in the 3 relevant files at once by doing this:
```
sed -i.bak -e 's/^\(\.ascii " -export:\\"\)_/\1/' libs/context/src/asm/jump_i386_ms_pe_gas.asm libs/context/src/asm/make_i386_ms_pe_gas.asm libs/context/src/asm/ontop_i386_ms_pe_gas.asm
```

So maybe the leading underscore should be removed in that section?

**Comment by Kojoley** [comment]
This was fixed in https://github.com/boostorg/context/pull/149

**Comment by olk** [comment]
ty

**Comment by excitoon** [comment]
Thanks @brechtsanders !

I'll leave it here for future guys, there is same problem when you link MSVC object files with mingw, it seems impossible to specify `__declspec(dllexport)` right in the code.
