### ISSUE TITLE
deprecated header included

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/coroutine#53]
The file `<boost/detail/scoped_enum_emulation.hpp>` is being included here:
https://github.com/boostorg/coroutine/blob/8df277dc820701e6a62f5ae4018e7b7190490eb8/include/boost/coroutine/exceptions.hpp#L14

The problem is that this file is deprecated and causes warnings for any Beast or Asio users who use Asio's coroutines. Could we perhaps fix this for the release?

**Comment by olk** [comment]
Is a pre-C++11 equivalent available?

**Comment by vinniefalco** [comment]
Yes, here:
https://github.com/boostorg/core/blob/develop/include/boost/core/scoped_enum.hpp
